const MILLISECONDS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;

const DEFAULT_HTTP_TIMEOUT_SECONDS = 8;
const OPENAI_REQUEST_TIMEOUT_SECONDS = 25;
const SESSION_CLEANUP_INTERVAL_MINUTES = 5;

const HTTP_TOO_MANY_REQUESTS_STATUS = 429;
const HTTP_BAD_GATEWAY_STATUS = 502;
const HTTP_SERVICE_UNAVAILABLE_STATUS = 503;
const HTTP_GATEWAY_TIMEOUT_STATUS = 504;

export const DEFAULT_HTTP_TIMEOUT_MS = DEFAULT_HTTP_TIMEOUT_SECONDS * MILLISECONDS_PER_SECOND;

export const MAX_RETRY_ATTEMPTS = 1;

export const RETRY_BASE_DELAY_MS = 300;

export const RETRY_BACKOFF_FACTOR = 2;

export const RETRYABLE_STATUS_CODES: readonly number[] = [
  HTTP_TOO_MANY_REQUESTS_STATUS,
  HTTP_BAD_GATEWAY_STATUS,
  HTTP_SERVICE_UNAVAILABLE_STATUS,
  HTTP_GATEWAY_TIMEOUT_STATUS
];

export const SESSION_CLEANUP_INTERVAL_MS =
  SESSION_CLEANUP_INTERVAL_MINUTES * SECONDS_PER_MINUTE * MILLISECONDS_PER_SECOND;

export const OPENAI_REQUEST_TIMEOUT_MS = OPENAI_REQUEST_TIMEOUT_SECONDS * MILLISECONDS_PER_SECOND;

export const HTTP_NOT_FOUND_STATUS = 404;

export const MAX_FORECAST_DAYS = 5;

export const HTTP_SUCCESS_MIN_STATUS = 200;

export const HTTP_SUCCESS_MAX_STATUS = 299;
